### List available browsers
GET {{apiUrl}}/browsers
authorization: Basic {{apiKey}}:

### List available locations
GET {{apiUrl}}/locations
authorization: Basic {{apiKey}}:

### Get test state
< {%
    request.variables.set("testId", "") // fill the id
%}
GET {{apiUrl}}/tests/{{testId}}
authorization: Basic {{apiKey}}:

### Get test report
< {%
    request.variables.set("reportId", "") // fill the id
%}
GET {{apiUrl}}/reports/{{reportId}}
authorization: Basic {{apiKey}}:
